# Generated by Django 3.0.3 on 2020-02-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('seq_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('gpoint', models.CharField(max_length=100)),
                ('dangci_text', models.CharField(max_length=20)),
                ('dangci', models.IntegerField()),
                ('image_url', models.CharField(max_length=1024)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website_app.City')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('sight_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('score', models.FloatField(default=0.0)),
                ('intro', models.CharField(max_length=1024)),
                ('point', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('sale_count', models.IntegerField(default=0)),
                ('image_url', models.CharField(max_length=1024)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website_app.City')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRatingStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_count', models.IntegerField()),
                ('neutral_count', models.IntegerField()),
                ('negative_count', models.IntegerField()),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_stat', to='website_app.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelComment',
            fields=[
                ('feed_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('feed_type', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_app.Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='website_app.Province'),
        ),
    ]
