# Generated by Django 3.0.3 on 2020-02-15 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qunar', '0002_hotelcollection_sightcollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sightcollection',
            name='user',
        ),
        migrations.AddField(
            model_name='hotel',
            name='user_liked',
            field=models.ManyToManyField(related_name='hotels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sight',
            name='users_liked',
            field=models.ManyToManyField(related_name='sights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HotelCollection',
        ),
        migrations.DeleteModel(
            name='SightCollection',
        ),
    ]
