# Generated by Django 3.0.3 on 2020-02-20 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qunar', '0003_auto_20200215_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='qunar.City'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sights', to='qunar.City'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='sight_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
